### ISSUE TITLE
Building frontend..

### ISSUE THREAD

**Issue by Timtech4u** [danidee10/chatire#1]
Hi @danidee10 , is it possible to have the Vuejs frontend built and used by Django instead of running it on another server.

**Comment by danidee10** [comment]
Yes it's very possible. I'll push a new branch that implements it this night.

**Comment by Timtech4u** [comment]
Cool. Thanks

**Comment by danidee10** [comment]
I've pushed a new branch called `heroku`. just switch to it with

```bash
$ git checkout heroku
```

and running `python manage.py runserver` should serve the Vue application.

Note if you make changes to the Vue app. You have to run `npm build`. It can take time. that's the reason why the webpack dev server is included because it picks up changes *almost* instantly.

So you can use the dev server to test and when you're ready to deploy you can run `npm build`.

**Comment by Timtech4u** [comment]
Thanks @danidee10  , this is exactly what I needed.
